export const BUSINESS_INFO = {
  name: "ASHTON TURNER",
  email: "VickyMcdonald8462@outlook.com",
  phone: "+1 3075072947",
  address: {
    street: "Jackson Court 6592",
    city: "Littleton",
    state: "Colorado",
    zip: "80130",
    country: "United States",
  },
  fullAddress: "Jackson Court 6592, Littleton, Colorado 80130, United States",
  shortAddress: "Littleton, Colorado",
} as const;

export const CATEGORIES = [
  {
    id: "feeders",
    name: "Smart Feeders",
    description: "Automatic feeding solutions",
    icon: "Utensils",
    href: "/shop/feeders",
  },
  {
    id: "fountains",
    name: "Smart Water Fountains",
    description: "Fresh water, always",
    icon: "Droplets",
    href: "/shop/fountains",
  },
  {
    id: "trackers",
    name: "GPS Trackers & Collars",
    description: "Never lose your pet",
    icon: "MapPin",
    href: "/shop/trackers",
  },
  {
    id: "cameras",
    name: "Pet Cameras",
    description: "Watch & interact remotely",
    icon: "Camera",
    href: "/shop/cameras",
  },
  {
    id: "litter",
    name: "Smart Litter & Sensors",
    description: "Automated hygiene",
    icon: "Sparkles",
    href: "/shop/litter",
  },
  {
    id: "toys",
    name: "Interactive Toys",
    description: "Smart play experiences",
    icon: "Gamepad2",
    href: "/shop/toys",
  },
  {
    id: "health",
    name: "Health Monitoring",
    description: "Track pet wellness",
    icon: "Heart",
    href: "/shop/health",
  },
] as const;

export const PRODUCTS = [
  {
    id: "1",
    name: "SmartFeed Pro 3000",
    category: "feeders",
    price: 149.99,
    originalPrice: 189.99,
    rating: 4.8,
    reviews: 342,
    image: "/products/feeder-1.jpg",
    badge: "Best Seller",
    features: ["Wi-Fi Connected", "App Control", "Portion Control"],
    petType: ["dog", "cat"],
  },
  {
    id: "2",
    name: "AquaPure Smart Fountain",
    category: "fountains",
    price: 79.99,
    rating: 4.7,
    reviews: 218,
    image: "/products/fountain-1.jpg",
    features: ["Filter Alerts", "LED Indicator", "Ultra Quiet"],
    petType: ["dog", "cat"],
  },
  {
    id: "3",
    name: "PetTrack GPS Collar",
    category: "trackers",
    price: 129.99,
    originalPrice: 159.99,
    rating: 4.9,
    reviews: 567,
    image: "/products/tracker-1.jpg",
    badge: "Top Rated",
    features: ["Real-time GPS", "Geo-fencing", "Activity Tracking"],
    petType: ["dog"],
  },
  {
    id: "4",
    name: "HomeWatch Pet Camera",
    category: "cameras",
    price: 199.99,
    rating: 4.6,
    reviews: 423,
    image: "/products/camera-1.jpg",
    features: ["1080p HD", "Treat Dispenser", "Two-way Audio"],
    petType: ["dog", "cat"],
  },
  {
    id: "5",
    name: "AutoClean Litter Box",
    category: "litter",
    price: 449.99,
    originalPrice: 549.99,
    rating: 4.5,
    reviews: 189,
    image: "/products/litter-1.jpg",
    badge: "Premium",
    features: ["Self-Cleaning", "Odor Control", "Health Monitoring"],
    petType: ["cat"],
  },
  {
    id: "6",
    name: "PlayBot Interactive Toy",
    category: "toys",
    price: 59.99,
    rating: 4.4,
    reviews: 312,
    image: "/products/toy-1.jpg",
    features: ["AI Movement", "App Control", "Auto-play Mode"],
    petType: ["cat"],
  },
  {
    id: "7",
    name: "VitalPet Health Monitor",
    category: "health",
    price: 249.99,
    rating: 4.7,
    reviews: 156,
    image: "/products/health-1.jpg",
    badge: "New",
    features: ["Heart Rate", "Activity Level", "Sleep Tracking"],
    petType: ["dog", "cat"],
  },
  {
    id: "8",
    name: "SmartBowl Duo",
    category: "feeders",
    price: 89.99,
    rating: 4.6,
    reviews: 278,
    image: "/products/feeder-2.jpg",
    features: ["Weight Sensor", "Portion Tracking", "Multi-pet"],
    petType: ["dog", "cat"],
  },
] as const;

export const TRUST_BADGES = [
  { icon: "Shield", label: "Secure Checkout" },
  { icon: "Headphones", label: "Fast Support" },
  { icon: "RefreshCw", label: "Easy Returns" },
  { icon: "BadgeCheck", label: "Verified Business" },
] as const;

export const NAV_LINKS = [
  { href: "/", label: "Home" },
  { href: "/shop", label: "Shop" },
  { href: "/about", label: "About" },
  { href: "/trust", label: "Why Trust Us" },
  { href: "/contact", label: "Contact" },
] as const;

export const POLICY_LINKS = [
  { href: "/policies/terms", label: "Terms & Conditions" },
  { href: "/policies/shipping", label: "Shipping Policy" },
  { href: "/policies/returns", label: "Returns & Refunds" },
  { href: "/policies/privacy", label: "Privacy Policy" },
] as const;
